### PR TITLE
change stdin to piped

### PR DESCRIPTION
**Pull request by dakom**
See https://github.com/sagiegurari/cargo-make/issues/355

### CODE REVIEW

**Comment by sagiegurari** [comment]
I ran a simple test in which i created a task that reads user input as follows:

```toml
[tasks.input]
script =[
'''
echo reading..
read vv
echo read $vv
'''
]
```

with pipe this breaks so its not working well.
we either need a different solution or to enable to set it from outside.
the ability to read user input is critical in case commands require user password (for example if we do sudo).

**Comment by dakom** [comment]
making it a config option, and having the default be `inherit`, sounds good to me!

**Comment by dakom** [comment]
how about making the config options an enum that accepts Null, Pipe, or Inherit? (default will be inherit)

**Comment by dakom** [comment]
will add to the PR - one min

**Comment by sagiegurari** [comment]
and what in cargo-make will tell you to choose that or the default?

**Comment by dakom** [comment]
thinking instead of `capture_output` being a bool, it could be a string accepting "null", "inherit", or "pipe" - and then add a new one doing the same for `capture_input`

**Comment by dakom** [comment]
added to the PR... lemme know what you think :)

**Comment by sagiegurari** [comment]
don't think you understood my point.
1. pipe breaks the script invocation
2. what would in cargo make tell runscript if to use pipe or not. its ok that runscript allows external flag but what is different between my read input script that breaks and you npx script that hangs that will make cargo-make provide a different value.
3. capture output shouldn't control input. its hacky.

**Comment by dakom** [comment]
> 1. pipe breaks the script invocation

depends on what you're running, no? in some scenarios `inherit` breaks things too, which is why I'm saying to make it configurable but [leave the default as `inherit`](https://github.com/sagiegurari/run_script/pull/9/commits/b8b6ec73ab82d4de4f301916cd1a4e1fdfb3cd13#diff-dfd26227c4842bd3288e9b1f53f0089fR91)

> 2. what would in cargo make tell runscript if to use pipe or not. its ok that runscript allows external flag but what is different between my read input script that breaks and you npx script that hangs that will make cargo-make provide a different value.

`cargo-make` should provide the options to `script` tasks imho. So in addition to options like `script_runner` and `script_extension` I'm suggesting you add `capture_input` and `capture_output` which will each accept "null", "pipe", or "inherit". If nothing is supplied nothing is passed and `run_script` use its defaults (which are unchanged from before - input is inherit and output is pipe)

> 3. capture output shouldn't control input. its hacky.

I agree - not sure where you're seeing that?

**Comment by dakom** [comment]
Since the options here would be specific to scripts, better names for those might be `script_capture_input` and `script_capture_output`

**Comment by sagiegurari** [comment]
2. this seem too verbose. wish there was a way to support both. that would be best solution. users shouldn't care about that.
maybe we can pass signals to child process? not sure....
i think this one needs more investigation

3. you are right. my mistake.

**Comment by dakom** [comment]
I agree that this PR is not the ultimate end goal, though it does make it more flexible and lets `cargo-make` have more decision... 

On the cargo make side, it doesn't feel that verbose to me but obviously it's your call!

Just to have it on the table, we're talking about most scripts being totally unchanged:

```toml
[tasks.input]
script =[
  '''
    echo reading..
    read vv
    echo read $vv
  '''
]
```

But some edge cases like launching webpack-dev-server have an extra line or two:

```toml
[tasks.input]
script_capture_input = "null"
script_capture_output = "inherit" # or "pipe"? whatever..
script =[
  '''
    npx webpack-dev-server --config webpack.dev.js
  '''
]
```

gonna call it a night for now. later!

**Comment by dakom** [comment]
imho it makes sense to merge this change here, and then the question for how to expose it in `cargo-make` is a different one

as far as I can see, it's possible to keep `cargo-make` exactly as it is from the user's perspective even if this change is merged here

(though I do think cargo make should add the `script_capture_*` stuff as a configurable option - we could open up an issue there to continue the discussion?)

**Comment by sagiegurari** [comment]
ok agree

**Comment by dakom** [comment]
cool. not sure how to resolve the codecov stuff... if there's anything I can do to help there let me know

**Comment by sagiegurari** [comment]
@dakom i'm merging this one. will do few more small changes/tests.
thanks a lot!!!

**Pull request merged**
